### ISSUE TITLE
update disgord to v0.21 or higher

### ISSUE THREAD

**Issue by andersfylling** [pazuzu156/atlas#1]
Hi, I've looked into this cool project a few times and I wanted to notify you that discord api v6 is deprecated. So I advice you to update your disgord version. 

The disgord interface has been heavily modified, and things are a bit compartmentalized now. Before context was mandatory, but is now optional.

example:
```go
client.On(disgord.EvtMessageCreate, someHandler)
```
has been removed, instead you are forced to use a builder:
```go
client.Gateway().MessageCreate(someHandler)
```

For Controller and Middlewares:
```go
client.Gateway().
	WithMiddleware(notByBot, hasPrefix("!")).
	WithCtrl(&disgord.Ctrl{Runs: 5}).
	MessageCreate(someHandler)
```

Gateway logic is found in `client.Gateway()`, as such the connect, disconnect, etc. has been moved into there.

REST methods are organized by their resource:
```go
client.GetGuildMember(context.Background(), guildID, memberID)
```

has now become:
```go
client.Guild(guildID).Member(memberID).Get()
```

For cancellation:
```go
client.Guild(guildID).Member(memberID).WithContext(deadline).Get()
```

Voice has been moved as well
```go
//v0.21
client.Guild(guildID).VoiceConnect(channelID, false, true) // ish, i think

// v0.22
client.Guild(guildID).VoiceChannel(channelID).Connect(false, true)
```

**Comment by pazuzu156** [comment]
Interesting. That'll require some work, interested to see how things will turn out with this

**Comment by andersfylling** [comment]
The interface is starting to become finalized, so on the positive side there won't be a drastic change of the basic API again
